USE [master]
GO

/****** Object:  Database [OnlineLibrary-Asp.net]    Script Date: 01.05.2019 14:45:32 ******/
CREATE DATABASE [OnlineLibrary-Asp.net]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnlineLibrary-Asp.net', FILENAME = N'C:\Users\pati\OnlineLibrary-Asp.net.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OnlineLibrary-Asp.net_log', FILENAME = N'C:\Users\pati\OnlineLibrary-Asp.net_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnlineLibrary-Asp.net].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET ARITHABORT OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET  ENABLE_BROKER 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET  MULTI_USER 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET QUERY_STORE = OFF
GO

USE [OnlineLibrary-Asp.net]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OnlineLibrary-Asp.net] SET  READ_WRITE 
GO

